spring:
  application:
    name: demo-outbox-debezium-avro
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  kafka:
    schema-registry-url: http://localhost:8081
  outbox:
    purge:
      cron: "0 0 6 * * *"
      retention-period-days: 30

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    use-root-path: true
